spring.application.name=ToDoListApplication

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/to_do_list
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Hikari CP
spring.datasource.hikari.maximum-pool-size=8

server.servlet.session.timeout=2h